import Foundation

// An ordered array keeps generated output deterministic.
let marks: [(scalar: UInt32, rows: [String])] = [
  (0x300, ["##...", ".##..", "..##."]),  // grave
  (0x301, ["...##", "..##.", ".##.."]),  // acute
  (0x302, ["..#..", ".###.", "##.##"]),  // circumflex
  (0x303, [".##.#", "#.##."]),  // tilde
  (0x304, ["#####"]),  // macron
  (0x306, ["#...#", ".###."]),  // breve
  (0x307, [".##..", ".##.."]),  // dot above
  (0x308, ["##.##", "##.##"]),  // diaeresis
  (0x30A, [".###.", ".#.#.", ".###."]),  // ring
  (0x30B, [".#..#", "#..#."]),  // double acute
  (0x30C, ["##.##", ".###.", "..#.."]),  // caron
  (0x327, ["..#..", "...#.", ".##.."]),  // cedilla
  (0x328, ["..#..", ".#...", ".##.."]),  // ogonek
]
let supportedMarks = Set(marks.map(\.scalar))
var entries: [(scalar: UInt32, base: UInt32, mark: UInt32)] = []
for value in UInt32(0xC0)..<UInt32(0x250) {
  let decomposition = Array(String(UnicodeScalar(value)!).decomposedStringWithCanonicalMapping.unicodeScalars)
  guard decomposition.count == 2 else { continue }
  let base = decomposition[0].value
  let mark = decomposition[1].value
  guard (0x41...0x5A).contains(base) || (0x61...0x7A).contains(base),
    supportedMarks.contains(mark)
  else { continue }
  entries.append((value, base, mark))
}

func hex(_ value: UInt32, digits: Int = 4) -> String {
  let text = String(value, radix: 16, uppercase: true)
  return "0x" + String(repeating: "0", count: max(0, digits - text.count)) + text
}

var lines = [
  "// Generated by LatinCompositionPlugin. Do not edit by hand.",
  "// Canonical Latin compositions only; deliberately not a general Unicode shaper.",
  "enum LatinCompositions {",
  "  static let entries: [(scalar: UInt32, base: UInt32, mark: UInt32)] = [",
]
lines += entries.map { "    (\(hex($0.scalar)), \(hex($0.base, digits: 2)), \(hex($0.mark)))," }
lines += ["  ]", "", "  static let marks: [UInt32: [String]] = ["]
lines += marks.map { mark in
  let rows = mark.rows.map { "\"\($0)\"" }.joined(separator: ", ")
  return "    \(hex(mark.scalar)): [\(rows)],"
}
lines += ["  ]", "}", ""]

enum GeneratorError: Error {
  case usage(String)
}
guard CommandLine.arguments.count == 2 else {
  throw GeneratorError.usage("Usage: LatinCompositionGenerator OUTPUT.swift")
}
let destination = URL(fileURLWithPath: CommandLine.arguments[1])
try lines.joined(separator: "\n").write(to: destination, atomically: true, encoding: .utf8)
print("Generated \(entries.count) Latin compositions: \(destination.path)")
