import Foundation

@main
struct WaylandSourceGenerator {
  static func main() throws {
    guard CommandLine.arguments.count == 4 else {
      print(
        """
        WaylandSourceGenerator is an internal Chroma build tool and is not a demo.

        Run the remote rendering daemon on Linux:
          swift run --package-path Example RemoteDemoDaemon

        To accept connections from another machine, specify this host's IP:
          swift run --package-path Example RemoteDemoDaemon <linux-host-ip>

        Or run a local graphical demo:
          swift run --package-path Example ChromaDemo
        """
      )
      return
    }

    let vertexURL = URL(fileURLWithPath: CommandLine.arguments[1])
    let fragmentURL = URL(fileURLWithPath: CommandLine.arguments[2])
    let outputURL = URL(fileURLWithPath: CommandLine.arguments[3])
    let vertexSource = try String(contentsOf: vertexURL, encoding: .utf8)
    let fragmentSource = try String(contentsOf: fragmentURL, encoding: .utf8)
    let hashes = rawStringHashes(for: [vertexSource, fragmentSource])

    let generated = """
      // Generated by WaylandSourcePlugin. Do not edit.
      let vertexShader = \(hashes)\"\"\"
      \(terminated(vertexSource))\"\"\"\(hashes)

      let fragmentShader = \(hashes)\"\"\"
      \(terminated(fragmentSource))\"\"\"\(hashes)

      """

    try FileManager.default.createDirectory(
      at: outputURL.deletingLastPathComponent(),
      withIntermediateDirectories: true
    )
    try generated.write(to: outputURL, atomically: true, encoding: .utf8)
  }

  private static func rawStringHashes(for sources: [String]) -> String {
    var hashes = "#"
    while sources.contains(where: { source in
      source.contains("\"\"\"\(hashes)") || source.contains("\\\(hashes)(")
    }) {
      hashes += "#"
    }
    return hashes
  }

  private static func terminated(_ source: String) -> String {
    source + (source.hasSuffix("\n") ? "" : "\n")
  }
}

enum GeneratorError: Error, CustomStringConvertible {
  case usage

  var description: String {
    "usage: WaylandSourceGenerator <vertex-shader> <fragment-shader> <output.swift>"
  }
}
