import Foundation

enum GeneratorError: Error {
  case usage
  case invalidCoverage
}

guard CommandLine.arguments.count == 3 else { throw GeneratorError.usage }
let source = URL(fileURLWithPath: CommandLine.arguments[1])
let destination = URL(fileURLWithPath: CommandLine.arguments[2])
let data = try Data(contentsOf: source)
let bytes = [UInt8](data)
let expectedCount = 95 * 60 * 84
guard !bytes.isEmpty, bytes.count % 3 == 0 else { throw GeneratorError.invalidCoverage }
var pixelCount = 0
for index in stride(from: 0, to: bytes.count, by: 3) {
  let count = Int(bytes[index]) << 8 | Int(bytes[index + 1])
  guard count > 0, count <= expectedCount - pixelCount else {
    throw GeneratorError.invalidCoverage
  }
  pixelCount += count
}
guard pixelCount == expectedCount else { throw GeneratorError.invalidCoverage }
let encoded = Array(data.base64EncodedString())
let chunks = stride(from: 0, to: encoded.count, by: 100).map { start in
  "\"" + String(encoded[start..<min(start + 100, encoded.count)]) + "\""
}.joined(separator: "\n    + ")
let output = """
// Generated by BundledFontPlugin; do not edit.
// Derived from Noto Sans Mono Regular 2.007; SIL OFL 1.1.
// Copyright 2015-2021 Google LLC. All Rights Reserved.
// See Resources/OFL.txt and README.md for license and source provenance.
import Foundation

enum BundledFont {
  static let firstScalar: UInt32 = 0x20
  static let lastScalar: UInt32 = 0x7E
  static let glyphWidth = 60
  static let glyphHeight = 84

  static let pixels: [UInt8] = {
    let encoded = [UInt8](Data(base64Encoded: encodedBase64)!)
    var result: [UInt8] = []
    result.reserveCapacity(Int(lastScalar - firstScalar + 1) * glyphWidth * glyphHeight)
    for index in stride(from: 0, to: encoded.count, by: 3) {
      let count = Int(encoded[index]) << 8 | Int(encoded[index + 1])
      result.append(contentsOf: repeatElement(encoded[index + 2], count: count))
    }
    precondition(result.count == Int(lastScalar - firstScalar + 1) * glyphWidth * glyphHeight)
    return result
  }()

  private static let encodedBase64 =
    \(chunks)
}

"""
try output.write(to: destination, atomically: true, encoding: .utf8)
