import Foundation

@main
struct ShaderGeneratorTool {
  static func main() throws {
    let arguments = CommandLine.arguments

    guard arguments.count == 4 else {
      print("Usage: ShaderGeneratorTool <package-directory> <output-file> <shaders-directory>")
      exit(1)
    }

    let packageDir = URL(fileURLWithPath: arguments[1])
    let outputFile = URL(fileURLWithPath: arguments[2])
    let shadersDir = URL(fileURLWithPath: arguments[3])

    try generateShaders(
      packageDirectory: packageDir,
      outputFile: outputFile,
      shadersDirectory: shadersDir
    )
  }

  static func generateShaders(
    packageDirectory: URL,
    outputFile: URL,
    shadersDirectory: URL
  ) throws {
    let vertexShaderURL = shadersDirectory.appendingPathComponent("vertex.glsl")
    let fragmentShaderURL = shadersDirectory.appendingPathComponent("fragment.glsl")

    guard FileManager.default.fileExists(atPath: vertexShaderURL.path) else {
      throw ShaderGenerationError.missingShader("vertex.glsl")
    }

    guard FileManager.default.fileExists(atPath: fragmentShaderURL.path) else {
      throw ShaderGenerationError.missingShader("fragment.glsl")
    }

    let vertexShader = try String(contentsOf: vertexShaderURL, encoding: .utf8)
    let fragmentShader = try String(contentsOf: fragmentShaderURL, encoding: .utf8)

    let generatedCode = generateSwiftCode(
      vertexShader: vertexShader,
      fragmentShader: fragmentShader
    )

    // Create output directory if it doesn't exist
    try FileManager.default.createDirectory(
      at: outputFile.deletingLastPathComponent(),
      withIntermediateDirectories: true
    )

    try generatedCode.write(to: outputFile, atomically: true, encoding: .utf8)

    print("Generated shaders successfully: \(outputFile.path)")
  }

  static func generateSwiftCode(vertexShader: String, fragmentShader: String) -> String {
    var result = "// This file is generated by ShaderGeneratorPlugin - DO NOT EDIT\n\n"
    result += "import Foundation\n\n"
    result += "extension Wayland {\n"
    result += "    /// Vertex shader for rendering quads with border support\n"
    result += "    static let vertexShader = \"\"\"\n"

    result += escapeShaderString(vertexShader)

    result += "\"\"\"\n\n"
    result += "    /// Fragment shader for rendering with borders and rounded corners\n"
    result += "    static let fragmentShader = \"\"\"\n"

    result += escapeShaderString(fragmentShader)

    result += "\"\"\"\n"
    result += "}\n"

    return result
  }

  static func escapeShaderString(_ shader: String) -> String {
    // Handle triple quotes in the shader content
    let escaped =
      shader
      .replacingOccurrences(of: "\\\"", with: "\\\\\\\"")
      .replacingOccurrences(of: "\"\"", with: "\\\"\\\"")
    return escaped
  }
}

enum ShaderGenerationError: Error, CustomStringConvertible {
  case missingShader(String)
  case generationFailed(String)

  var description: String {
    switch self {
    case .missingShader(let shader):
      return "Missing shader file: \(shader)"
    case .generationFailed(let reason):
      return "Shader generation failed: \(reason)"
    }
  }
}
