#!/usr/bin/env python3
"""Regenerate Chroma's single ASCII atlas. Requires Pillow 11.3.0 (offline tool only).
Download NotoSansMono-Regular.ttf from the pinned URL in ChromaFont/README.md,
then run: python3 Tools/rasterize-font.py /path/to/NotoSansMono-Regular.ttf
"""
import base64
import hashlib
import itertools
from pathlib import Path
import sys
from PIL import Image, ImageDraw, ImageFont

source = Path(sys.argv[1])
sha = "d9e2b23d19f8230be7146f409a52b1d23117e635e28f2e2892cf91b7382f325b"
assert hashlib.sha256(source.read_bytes()).hexdigest() == sha, "Unexpected font source"
font = ImageFont.truetype(str(source), 60)
assert font.getlength("M") == 36
pixels = bytearray()
for scalar in range(0x20, 0x7F):
    image = Image.new("L", (60, 84))
    ImageDraw.Draw(image).text((0, 65), chr(scalar), font=font, fill=255, anchor="ls")
    pixels.extend(image.tobytes())
encoded = bytearray()
for value, group in itertools.groupby(pixels):
    count = sum(1 for _ in group)
    while count:
        run = min(count, 65535)
        encoded.extend((run >> 8, run & 255, value))
        count -= run
b64 = base64.b64encode(encoded).decode()
chunks = '\n    + '.join('"' + b64[i:i+100] + '"' for i in range(0, len(b64), 100))
out = Path(__file__).resolve().parents[1] / "Sources/ChromaFont/BundledFont.swift"
out.write_text('''// Generated by Tools/rasterize-font.py; do not edit bitmap data.
// Derived from Noto Sans Mono Regular 2.007; SIL OFL 1.1.
// Copyright 2015-2021 Google LLC. All Rights Reserved.
// See Resources/OFL.txt and README.md for license and source provenance.
import Foundation

enum BundledFont {
  static let firstScalar: UInt32 = 0x20
  static let lastScalar: UInt32 = 0x7E
  static let glyphWidth = 60
  static let glyphHeight = 84

  static let pixels: [UInt8] = {
    let encoded = [UInt8](Data(base64Encoded: encodedBase64)!)
    var result: [UInt8] = []
    result.reserveCapacity(Int(lastScalar - firstScalar + 1) * glyphWidth * glyphHeight)
    for index in stride(from: 0, to: encoded.count, by: 3) {
      let count = Int(encoded[index]) << 8 | Int(encoded[index + 1])
      result.append(contentsOf: repeatElement(encoded[index + 2], count: count))
    }
    precondition(result.count == Int(lastScalar - firstScalar + 1) * glyphWidth * glyphHeight)
    return result
  }()

  private static let encodedBase64 =
    ''' + chunks + '\n}\n')
